const GENRE_NAME_MAP = {
  'Action': '动作',
  'Adventure': '冒险',
  'Avant Garde': '实验性',
  'Award Winning': '获奖作品',
  'Comedy': '喜剧',
  'Drama': '剧情',
  'Fantasy': '奇幻',
  'Girls Love': '百合',
  'Gourmet': '美食',
  'Horror': '恐怖',
  'Mystery': '悬疑',
  'Romance': '恋爱',
  'Sci-Fi': '科幻',
  'Slice of Life': '日常',
  'Sports': '运动',
  'Supernatural': '超自然',
  'Suspense': '悬疑惊悚',
  'CGDCT': '萌系',
  'Childcare': '育儿',
  'Combat Sports': '格斗',
  'Detective': '侦探',
  'Educational': '教育',
  'Gag Humor': '搞笑',
  'Gore': '血腥',
  'High Stakes Game': '赌博',
  'Historical': '历史',
  'Idols (Female)': '女偶像',
  'Idols (Male)': '男偶像',
  'Isekai': '异世界',
  'Iyashikei': '治愈',
  'Mahou Shoujo': '魔法少女',
  'Martial Arts': '武术',
  'Mecha': '机战',
  'Medical': '医疗',
  'Military': '军事',
  'Music': '音乐',
  'Mythology': '神话',
  'Organized Crime': '黑帮',
  'Otaku Culture': '宅文化',
  'Parody': '恶搞',
  'Performing Arts': '表演艺术',
  'Pets': '宠物',
  'Psychological': '心理',
  'Racing': '竞速',
  'Reincarnation': '转生',
  'Love Status Quo': '青梅竹马',
  'Samurai': '武士',
  'School': '校园',
  'Showbiz': '演艺圈',
  'Space': '太空',
  'Strategy Game': '策略游戏',
  'Super Power': '超能力',
  'Survival': '生存',
  'Team Sports': '团队运动',
  'Time Travel': '时间旅行',
  'Vampire': '吸血鬼',
  'Video Game': '游戏',
  'Visual Arts': '视觉艺术',
  'Workplace': '职场',
  'Urban Fantasy': '都市奇幻',
  'Seinen': '青年向',
  'Shoujo': '少女向',
  'Shounen': '少年向'
}

export function getGenreChinese(genre) {
  if (!genre || !genre.name) return ''
  return GENRE_NAME_MAP[genre.name] || genre.name
}
